### ISSUE TITLE
scanner() call missing the excludedirs variable

### ISSUE THREAD

**Issue by guzzard** [Citon/strangethings#3]
Row 222, "scanner(suffixlist, equivtypes, scandir)" need to be changed to "scanner(suffixlist, equivtypes, scandir, **excludedirs**)" otherwise python trows an error.

Thanks for a great script!

**Comment by pauldoom** [comment]
Thanks for the bug report! That is what I get for not testing a pull.  I corrected the issue and did a little cleanup.
